# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo OSS Theme"
license = "MIT"
licenselink = "https://github.com/tmobile/hugo-oss-theme/blob/master/LICENSE.md"
description = "Opensource theme by t-mobile"
homepage = "https://github.com/tmobile/hugo-oss-theme"
tags = ["magenta", "t-mobile"]
features = ["responsive", "community", "opensource"]
min_version = 0.18

[author]
  name = "tmobile"
  homepage = "https://github.com/tmobile/hugo-oss-theme"
