language: go
go:
- 1.8.x
branches:
  only:
  - master
install:
- go get -v github.com/spf13/hugo
- sudo pip install awscli
script:
- hugo --cleanDestinationDir
deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
  bucket: tmo-opensource-website-external
  local_dir: public
  skip_cleanup: true
  region: us-west-2
  on:
    branch: master
after_deploy:
- aws configure set preview.cloudfront true
- ./cdn-invalidate.sh
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: IhyCcjmOvoASGYioQd5o53nr1eUKbOcnIfGCBRxjTFgicvynGCKEGHqtAwksfVH1sOUauBNZKR9Ov2QyzWhQYY5ZzXV8F4/FlQ8NMkbi2x2lk6p94WOx2gIYa1tmRc2hEotwccmX4uHa83WKvDxfgXKZy51ioG04+dv22mJ7llW0wEr3Dwz6nyXZy4XpAiPL69EJ3zQr70ZVqjz9tyQqBC37YOIRdk8JC9kAhDOPLT2gwNNZRHLE8HJZV5wvZLIEw8ykOnfO/JZdtklJ5kKrixi2GFi7RQ7WGBLf8ILx/m4MG6dcp6J6HfJVHuJP5WNTKEl8mmtSHXS6WTlngqMZlrB2IIjIU6igszFEZPyGyN9Yp8VZ9DQKz20BA22+yu+CzlDS8AEr2JZyxJ0GOTnVHmUMfuOYgvhZPcRW1sLp/V7P8TQnWlNSJssgqu8ZvfI6cyKObJgdEMf9PsJRIOCPR6wroCBxkaE0wJQDN5+/2s5y3QNqCbDy86Ls2yQTibbC5eDw1iN5zstRgisMN/OYe97NOZ6hANec4azQPXppjVYiKKTgB2stSnJF3jrVa9zH4SPK4Z3hmftSlEhT5ubHeloXNRtzDm6J9pChcEF38/SMKCx0HVdAm03ywzB+61n09cx2yfsbBTxMTFYrCVIlmtOzJsWTVyR6tqpNKlk252o=
  - secure: qIXbiCY+LSlTDywLnirLBfyjmrZyQjDxTYRS/SXoqVl6/bdHk7U4rqIIow+QThbRBT2qj2utPnCR8L4+MEn8ahqMNfws6N0aXneD1kiJnIA8vqn75zU0rnTvhEp7cQjU25bt2ApfQOiz3ovUvn8gUBuoYUa94gEaYiGJ2EGZ3/H3zPy2vtIRSwa6IYjgMirDX9wdoI88HcfDlSEsUnChQP3jfnMp1Yqa5inhDlIc13yv4wF+6paLC0p5XC4xvzcnIeBQdQ2DoLDofTTmEFoyxFljHNIEwogJnEZIC5Z69TF+OMkDW1bHLhcyJBlzOjl0uoTBqciiYXe6C3wni9989BvTGEdQWfiWTA4uSR7m6u7IZ28jdmcxphr2E2MEjd98HL1RRS+ZNuNY9K1qn/PUUpHiErxFwp0CpVEw0o+FBba8gJvEplt6T4XMjxYb6lkIlip83WCwGqv9G4eFMvX+glhDYKAujCg/bDe0Dj20HVdy6+cYYGMo+llyHGmXLf7F91xTMTnm/Br4KjS1kBtCb3qzpQmds/DJoFtKOLMgJQJJd/bSRDcJzzmp6YUn/lal+Kz7Wue85Pq6L3AORUSBwWYVT6cfyjohI1vulOjTp5xr8PdhFXsfxml2qGMMJG5xUeM7operuZRiMTychPqP4HvtYikc9An8DP6wAp5ZXl0=
  - secure: znC6Ay96UPqfK7IG/N7P2WvfdcDISLFLTeL9+YaDLzqH+fbOQM8pXn/Fz0iAC9RYN35YwgKnFrwF/SGZDWK6uQIiMXiG/I0cl4R9Fb2zrDHkgPmMGARg/XxlTzsrCUHls0OggmCDTNSg5uKnMA9dpVfvNLxb3Fv0rSoSc2h80mcjI9WFeBv/jPcRYfZaXNkfZKepim6+VfUFROqYdPd3VnXoEnoxXPz0wodOsr4aIWobJaVmAmC7keFCLScKyhgQ4+81NGJvkg3B1b+g6mGlcYRChpdQ620BOoqaMCtp0Suz5HZLH0IAkLsQp/EBkYen5dPJgY9mtyNYVeu0cLbz6VZplHwcRSdjeWpnHKiu5cUp6tuIdlBb9XQsin+TNnNFdvC31kAx99XoAQY+3BPutw22Vb9NbAxX32CnPxCo1yInpUy+UqQMFhW9hjDGTxPGHXTPy1CCm78cGtuqvLHpkD9qnvrLzMehAxatZlH4BX/VA0FQ/ObiFJlA2VmVW8Xw5eYtIZIqlUAQ5q0ez9ax5V+n4asAAlPgTMwKyTusstAfTynCDD19wgDR3VmulF9DYbsyyFB/hNRh6aV/mDBiAOQrDBXV4OB+Tg7oR1vBuOWLmiZw1+AvlbaX+tPKZM4ZdaYJTBOSU49IOk0Vsuf4ZjQjK9X0eaGwInIX2TQf/WM=
  - secure: wDSz69Is6XRuZocCegfA3+qKMrpGoGnpBWu6niWWlr6bn61hVm5IlyOAObW7ggl01CtvKjq3JXs+Nh9UhLR8S5H+MMIyyimR4jogcIL2w9nvG2qqQLs9OH08lNfpmJENbXqE92XXz3PEmWzEqtXyPZkdPpobOOIpH/jvf8lHqSGERes+a2Z9OvIFoPoJ04C4j1I2qzmSSruHg6hs8HXmYH9OJQztK5kwOPqoKCxuPxuNyevBo/0YHVt8HYV5oskUXrXDRMGkDaUF0loeOdoBeuJd1jFI+BvAOwfQeJS/s92Jq7Ev1/fr3RtFLS+dgqYUfiaBVqGK7h5G9ZieYZglRj3ibzt5yB5Ryl24BCAzMnYAzMwjCbQq6xrOUUT7AbfehKeYvvDluWomwPj7wRB3ucQXw9Fe6jLb+hkqQ3Xg0W9c4iRAPn1E+5OT9mNaHSBfDf5WiF/cLn9mGp38L20aQE5DSmK9FYHVl8yAIHkX9APaM8a3ewU8IwXYTU1jn/vBd8CFQOwcrNUpTDn9X9hpFBAEvlzMIXbktXbN19Vyk8n/U1ggJfPkdYeZJ/6NcQU3j3mVf6HtaW9VBjBOOTxgyi0BkTeSBWrINP+tmZRue1FTWVGN/bndx6byn34IY1JqD5s8rNfI4xl9MrBiLkwUPv1f+0aEFuu4pUcJ2NQWIXk=
  - secure: RQIJBcrWWYwFxeWVBI4ZL/AcmMNR4UJlQZAWyupf1dF+mwDfXoRR0jUwL6UWdzVrKzHsMT0cvNVj00FbdGZfci3K1R9v5gjw2izJlxqiP/ksPQVDaevczSIf2zyLni7MOEHl/kFjY3nBs16N9jh2TOtePF59rN9tOQL/bs0jDgtZlYmazCwf9gpNhRf3rzl6dsH/UPnWiwGUlhVD5y9mYNLfnGAlJa2GNtX7uNGSCiedJHydNHHWar19CK1Nwn5KCcyymW6Pt5slY86QKZnA84U/tqsZbmVzASGAuNGd7v02t7cGiiH60SS82HrjeUYlgONGjQQKLZAnPiG7zE5oOlx/vKE0ZCX2yHoKjLE/VOqAcioJWL58tJ8ud9emBfRWwJnqgKm4SLMF1n2deRpCmSUAg0WXQ503DJM8RXn1f1KBk05kxiZLLwSLvHZOv8NYC1mlJMnwjd4Tl1B4zGHsJ9r/uoyzEUGZTXH1t7rJSSrvjsq6yT910D+H7r3nnYgAUU41Kedz9XWgU83kGupz+2P8bzc6m2uRbv+CcBQzyMC0fLCG+DfeL9+aE2RBD9bJK9Ie76QEFf2PU4EyHqNF9HofJY9+BTddM2wbZK4spceeBPxZ9W0k8V11ftk4iRxOxkwjlJ++8+0ufP6DPSkFR3SyAzNuLst71MOL3YIKqyI=
