language: go
go:
- 1.8.x
branches:
  only:
  - develop
install:
- go get -v github.com/spf13/hugo
- sudo pip install awscli
script:
- hugo --buildDrafts
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: tmo-opensource-website
  upload-dir: internal
  local_dir: public
  skip_cleanup: true
  on:
    branch: develop
after_deploy:
- aws configure set preview.cloudfront true
- "./cdn-invalidate.sh"
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: m8aS4LZpmBbWIruJGCVbkFsjSjv4bfDJZnxcQnp36If9Sog7SKFGMmQplyYkzpXaK1Hz/kKe7TexrjAbNNMGLQZA9nQkD4xKwJN0szuc0FbUWyiSkyfHvL1BaTLyR1Ivs/9EhVaSXroDAQ/dt9Mmgb81yc3bzHcKRoLV8Xj0VvHHveJP9Bm+eNNdSIxVHwjflygXtTtJptU89uuuHjzlql1F5fCO9k4gZQJvEmbo2lqyKpNZYSje2KAKC/4kTprjCUYo0KyxTCSUhBh1yHvT5gGheGBmVsO565hHUb9g1uyvAOMr1qraSKr8ejC0iO7KRXJNpMtMWvqV40gViUlUQEUp6SQ1pC0cN277zrTk8K0lO8kkZhWy+9xnKQXuMtKz4+gS/9xP1NwYI7M9NSu55zJ4Ok2rTBlYlJwdtKSeg0gm90ilz0ccc75OdWTAWP5tTnk3nTqpQ7IzHk7YgpDoHrbkN0CElQeEo4Ej6enKPcYs7tUE8/BPUDwSHYoMZ4RBSkC8sM+nsiNLY85HHSvY0clMOt5Va7BZ5Q4TvjYaQqhOufh9aolNScXDWuwtSJOyxiHVz9isreELEVPwzash2UQjMhdPHSUeo7FHthFUBwKkT0Y45nY/TZailmNGXhRXyCqlSy0cARyzazhIYjN3VL58t9jFLq12AALeJnx9Amg=
  - secure: vq4Z/GHVCDPHOkvIT043cOgthLvrRAo9NQp2MZfeD4lqMmUob7fCQe/xAkGXBOTSimVKtKXclUPeDx6oFrh6a+lx4mCATAsaspqZ/B/2aWBUQxKwnSfzpiP8403Ea+Vm3GqKG/YF2y/irT+DM3OlHOu6h7E4Wpx6xCsI5J6KaIVzyqMJvyT+mtw+R1eu/cS41nDS2coTyZFg6yr7PKyWq2ncoh+j0ciFlxY/pt599dsHpNTaC8RNMDDTQh/Dtr+pSxYU7KsrERPzD+vGQrwjiJSn9FQsH1XeRJRDpfgNnYhcyY3VSw3/BQmdU29gRqP3RZgz1RHO7RH6KGlRfeGtwHlIJcN9MMKDwWMOI7ZjJFyHu/6ytPdPKCP4CG0GNwfWoCYVHYGqk64F+5eJT0rH8hDHIKZffdqS1XzY0Pja64/mKWJWAdconk+nd8evTfBGqpJ6bxwy0CXDqHWrm0oB8BGt4J0EXltxYxNH9rWp7fn6GgGqBN2YspOxF4L0QRQ9mwU8jpLd4fs57ktxvvLvXoLM9YHB3hDVntZIaBEBhPwfgtNfTZAUPyB2yDqFUuKd8s/Dg7fzuv9SzhTWAtbdGsHmLSjmtJkYS611S94u0AHI3/2RDRbLv9CAdHL9bRyh28hAH5oEchKJ9Kyov4G39i5a74bAUj9yT1L3psoV/e4=
  - secure: LmXhB+LeaDVK25AN4uUjqh3vUDy0wlvIejvCdfF03BKrZN7cRRsEjrwxuRScRZDwTjyiEdYuCbaV4PSMKWC4M1oI7akyat2h2OOTaIO3f0xoqkl+3ybCf8KkUfz1Hg/UU1Dp//hsQvZSRYXrwWcRxFVs/OjIOTQ7G3u+FcUIcDoVTZsTvLU595bAp/av97mEJQDC8WxHiVxRK3PUg3nCjI7OJ6GV1b4I/y7AVZgSkqBHBNx2aaBr6vIyWTY+NhCMYFx0X8r4QRnk/qpUChmwpqe8QOPAJRhb2HXGdxjGgqCGryqPr0e1X3oQwLLOwRQb3u2fYW1wCi8/BIS1e1TvKAj86ol6muP8PQCghuX5FObA5gfQFMvYWunrALiwcyrG7pP7qeSbQtkOOh7AKit7te5GGtGqrkAwI96xAOnNCozZcBUWFIPBmyej7cXhfGDUW32XX1vyhCM2o7e8OzbY1r5QWwTthgj2shqi9s6WntMOo0p0Zj19RwM1sDIod7xoetn/aZm1m2WOwMwS1Kp/pRSUYvBB0ItE+D6ozPSiLsw4uULyGsagElrCnMZPHl1O2baDyAc6A+avvgZeKl276TNtumJDib5Ao48dWgRfisowszzbcBZGeSR7dwj4Ba0npBmhpJzLgwb/EOULDh+5e8l/oU33fU0vlvxRUpvBR8M=
  - secure: IaMw65mDT7q9gdm0T9ELKRF8qlszyRoalWLveeuRmjRPq8YAsXdg+A1BGpb+P+IQJ+9zESv00+bYbD+SgYMwMH8xNz7tTn1GLP6r4k+FfuPauoTBdEMeFJPqamsWGVjrZF+AKDKJthNQfCMH0RDNpcHcTKet6fXFZ8ad4+FciTDKJz2dYeXLHgZ1/AHskW7/k1t8/Azyhe1yg845JxtHkeVZA0nRiqdkhNIIjDDAaYO6ZR9wEWLS4TUgPcCxh98rOUhU5w8ayqmdrJzRm9mx9Bdax/9b4qV0KAU39hDQc8cTYS360oqJWaGYF7EWvrv3pQFHMxHezZvmCD+QEbgWgGHtIg++xNnhRosIBlwWh2+mQtX0o5UvmGxQ5lsbDBjgJY68WXYj2tEpdNSRaLnbENeuUQzBCqrbLnB80h2HvOxKvM/HrmVmVIaUx3Y1qQy01q7egQufE1ti0kvg45qHGeY33ZoprTyQl9Yi1rXgw/vclNTEslev5Uk86Bmd1v2WpwXxqqHU5VXprgkYIlQWTlj4X6suPu0kLmzyIflfQLPlykjRVGW83yxjiU4rcUJghbwPnkwmFJ10eD8iG9+pimfujmuwb2kdZJXTXJwjRBVm4UveQ0wJk0gbcEMI3ZFNn0RcLkUeOtgnVnZ4qvKXREHJb3Um8ScgL6TONIBrKxg=
  - secure: kUTo9TgI6bPigbrXG48nIMzgJ6PJe7gqL1iyeUvAxOO7jtoXjPKCkaA6ZY3v2nAeFc441xDh4lcZeSeExEjHXx/IIX1n5L1ttm4dkz2aLvUatkSS8q7zhFuU53xIPKxBtu00gSzyKAepaw2XJFY9iZbuv/APv6n84kHWBKaGO3V3agLZGfxe8ankohCq83IZ8fNkU4Kts2Qei7qKfka4a+XSmyT3KZF8NG3H90LxKPZNBSudIyZtTEu3YXsfw4aeOhSs8Lp001jtnHai1NR0p4mbnul4R8ObX9ry95NguPrX3P40VmbdmALcICYmMstOskUh1dyKxr4l/OE2w4o3XYgJQLBHLS/CAgfL1IhSSZeTB4k9qFiaRPdFCT5oMAep5Kelu+DcE6S6qVoc7tpK+IqeZCyjiPlX11nJetmchjj/osE12qxFD5gMWD4+FaMSnKMyZKN/1d5bjkFTqUg0nGPyihaBgBrfLQEvbft27rY5rSBpzaaV5+CIRs22WQghr0Xs7NGr6n/09ePhUXZkpcWX6cfuqUMnmkvRTIq/izluWfm3EY0o7SkbGmOs778A+QuYMiUYHpcsKms0IL3df2pQvEfU+A6uHJawIo90CJxcpP578P1Ah4NQ96tniCXa8VkwmEbCzgsVW2tzMC/VZYoYV5FGz2v/hdWnzm39Fto=
