language: go
go:
- 1.8.x
branches:
  only:
  - develop
install:
- go get -v github.com/spf13/hugo
- sudo pip install awscli
script:
- hugo --cleanDestinationDir
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: tmo-opensource-website
  local_dir: public
  skip_cleanup: true
  region: us-west-2
  on:
    branch: develop
after_deploy:
- aws configure set preview.cloudfront true
- "./cdn-invalidate.sh"
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: CxsShfMlhuFa1cBEfcvMQvTjxVyGK1ZIB0yuAzaaPCctCZ8Ad6aZMWfelXvIxsvC8TciAqo1OyaAqhvmoD8RkpzF/jIH5+13MuLxocuTeaVDHUGV1trSfQRg7Xk04Pw7953471uOXOaftzhYEToW3wNDQc6UCSzYhbKJTRRn8xE63Okng2pjT01capOwuICq8A8BqN1y++9jUzrOWp/C0rPLEfth1y8r+S3iMBS3sbC1OrhWdWcRiJYo9o/BHM0uTCGBdNbnBbQiym3Am/gIwy+onDGTO4BrxvfxuRaRPVmvQDKu973aDZ9sPzuD2IbqRFQZL6L70I5adXZj2j0qJi3Ag23X9t9c53259H3ifX5CKdr1rKoIvYXFjouegyoo2W3E5knW0Y1CjAUv5RaMeWvIHkY17w2k4/fmbVDZjbkUUN8Ejmec2CEwx0zPHNm3vKL7W2fbYdpap8eDCl48q7wN3/Twdxt1RQheMztchQc5b+RRZEoChQI+1bu/ruWOUoeyZuGB1+j1i1sEfcdCylqtdKRfyWYfstmUljlyR5C/6qAK0rQKEzlqMqXCUvqdjeNMg5cpeNYL5q8i3eRYlblEAupDe2n2WGblVYHyh2zd0ZYoBL5GAuoGNekzKMHYAxi48gFHTNGmU8VTz5knhU9WrwRtMeGAUEuxc5xsVPU=
  - secure: EQSFFUxhHHIq0ZJkv6d/K5jxDnk03bGzG3rhewWseeK7C+kmhp3x4ZpdDoB2LmXfolvxdvlsAAeFzkJdX2yknkTn5sofAo0C1apAHHxubd4ohENJAiCiZoqooz+8Il8QEuQ7nrMr5eFxmLlZn8wQoed2vQ+WkAhec9yBYl1pZUWkCxqcfxpRb5sgjX8IpINnASLXddGUWSxsbvZTtZnnfNIB4LdsLOLCT0GVElJWuDUZaEZZz3U2aOUl6i2PvsYYjwTC8QzRSADcD24xEm7CD3FDPcCo1Cb7VJVdpGiVJ2uQPYAAySI5RBeFNNBfisZiJbqHYW3DUTZZ+/20I/t+WOqGlYUjeIQYDhPluYKeijfFPuMOLxLRi4O2oJ58EmE6I9R1chVPDRLNgxRFbnLRDixZYykSZzjBkn6B8mTxYIH15zO9Jh/hv1IOsdqMo9MvOXNc/u6PF3CtlZmOPhmsRsBzTMVTcfXAAFXt30tlEJLkny+x1Jk4vqCQ8R+jHZsqWWgJGwmbul49VfhrtF/AoqX4KYEo5Fl6tgVVMtnURSS9xA+MB560Rd1vswzRE0UOEMLIVTBg1zEuAwPfBN7mof3yhtwCqxXq5ryeSrsuoP7n/WpuBciErOS4vLzLIVKwgXIsksYXH3UDUkR5rkU/eKrV70yvsdOZl8LicK4upIM=
  - secure: ZcOkYCbLhsfBv1fmVqW5jH6ymY9HuKbRGgCoorlzKvDYrce+QVim4HQSp9BKN5oP5JpmJ+tP7rs5iLw8J8yWtQUT+o7hcS/jFFiFqNslRIjkEX6pqE8IboHrfXrV8rVTVFFz9A4lekS/d3KFhkJHWbQGgOrfHMV7sC1NQjCM/eC11ZCdaRAQv2yVtSt7UrTZCRgREY3j9sZO8Pcf5RHfngqD8VlmKfvICBwuXlfHIm206kIqx/fKOJDFG9jQsBNWETDC8xqDPhQYSU2/KG49SbtwUeNXnATJlmZysyyp4sFnj0eiCVjfx7VJtE4MRQ0ZQ+xZ2xwfpZZXj9js+S5hy0Mfsge+kEm3WeMWOtsZZKuIybH7fHyZVQWW5CVV44D+NPqksSDKpK3FXnr5LdxTt3TTlYDxoPS0DAHVsbhsltabdqtk3yhtzAVGwFAJeRTSn4XK8sFbtjYRNVT2UpcDv2LtSMVdwHxKDmW2OWfjc/ajfroULOB9T7W/C9bTCWvnCblNonLh7f1aQqWKr6eMI7wJTJRn/DOYFT4DiMzb+Oxeig2M2mszk9T0DM8batHm1sGpbX2fgpm2xD6U55A3mh8vcSsz9poLhlbAnUx8ghxtWf4kOsGqn6+8P1wpSCrgAv2qwVfdRiLqR9LriHm9TLzgRBq5ElyVMzAvPvhT0Vs=
  - secure: kk/+j4oB4NpWTxfdC6PfcOANkJQK54plYSNY0mnoVkXSNOP1Bq/AmUIJfsD4IoHqqzXHxo4xGB4dI2DOcKBM9NevQbwkLs28h+l/QaHLV3EoggEXIi71xm4c99ThW3w24UnOgUfi2ZFR5IbmHr+9R7LuF9czE8YjYNN2sEK8z/Cg610Vf4NYPJZonTYjvGM7RgNYXIgPiX1a9U4QB1JcDblo0upp+Wz6gquKl6wageIZypqKdKM0ebvJXEDOqCtvb09ENiBbEpH5+FiWHPCsioNQt1gVX8BPz2WHgIQe9VsLHOikhGXGZgNFvXGZ0GqcOu00z43GEasu31ArBYfoGcmjn3E63K2I+pPNuXlqKHUiSfPDy64cjFJeMIE7JRxrRBsIRTRtrX2pJvniARuq04uHor7OCgN5Fz1oIRGem7lDuSXfxlLNsELEdJ7u/ZXhkW02qDNpOMzcGIvrDtV0uI1OkZpoXZhurx/fB4puRsrRnnW47e/js3Whg/vw31iQXLnHG9M1ndmtG+xdyJ6A5qnNbe5XhfWiYvvm6svy49BQal4pujCU7nN+wUnW6+7QS39uQZMaywp0oJRD6ESvKH0sMQkaHp3l8y7To4yszdjmXI3afdWjHnfmnLnxexjfc/iLbm3hVzDNXnE2VlRZ87JhtZ1ceIhSoVHvGNAud7g=
  - secure: aDSHNKghhojjSLN6JQyXkLRN+95vv0HpcsM6waF7dwkRMsMaN/nxwEO4qZQTpWO+hRryHKoEs0QXE3iWnY3PYOUlZdGZs7g8um7N01S8gp51VjkZs1i+Agnu8ljaE8PJmQYOmLEfOw4qgmsaGVl7QU75PQ3O+NNehyz7Hi+mi8pMqD+um1Lp2srNAVFvq9nzEUH5hE5oY5bdr7JEYyqXb9X7EGdST8LCn0fXQhp9m25k9Qwm80RR2ZcybXIaf+T2ISy7iYzikws6MI25pQ6C4becVoHOipOZFUEM6JYZL4XT9IPKPBXMSyZQSaQQ+czsSocf9BARgy9F5euOH/ybXKhRdiZL7p+IeRMKbipxBpmsqRAkigitS0JILEpWRLT2V9ZkxCpR5TriwMB/RPL+vCrUxD10/zZKvEuFCmpLDJo3FJkGooBDo1ApPuiQGEFmJhRKSi06uq30Sd7J2PInspOvTed4l3i/q7Ue8EJovbJQ8PMZqydIry3DCws2fqvno0mD7JYMY9RaWgqmAvAKnoKpmZrLjy++pE3jHAWa3WZPCBWCgSozdUxa33uKZ1M06EQw+B1nYUBdSI8Ikb0P+iqyfoh4iHz6Mt+WxP+GsIaPo3Yw0Zq/SoWAXYFuAsPfmvWe7MXTrCFEY0cqLBVa0sXUHPAV+jwaZT49ox0Lh/Q=
