language: go
go:
- 1.8.x
branches:
  only:
  - develop
install:
- go get -v github.com/spf13/hugo
- sudo pip install awscli
script:
- hugo --buildDrafts
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: tmo-opensource-website
  local_dir: public
  skip_cleanup: true
  on:
    branch: develop
after_deploy:
- aws configure set preview.cloudfront true
- "./cdn-invalidate.sh"
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: Za+lfYHZZXArfF043AdgpdOzpOpbZi40VS0OpSLTu/AXtwFf9dawa9j1la55/IRGURPN25ksemq7lSxfwNz4/8s9qGaa/bzwV5QCt6tzji3ieri+5hRc119sLEaJWCfHrOYqEIU36mLGknHQmxbtCuwwy3nsIjV2NGSb8fzor+UXPZdXVHvv1W3F7vwGCcMVk5+Z3mt4ytbo5llQ6CIBeoUMRaq1uP8ItMng30A86kDkkVs6Da08qQdn36ot8i+3M8tRk6Kq1cgBa8/QFkANo9BmLgIrF6YD06wsNIarfluMBLjNYBzMkpgQeRDDvgeAD59PfUtP/Nm26RkrHqraRjXtZfzt8SFW/CA0yMmw/EPWsQ/iuLVyWbi5kdaJhs3pOn+BI7Vzu4rJhx8DpPX848LOYcHCVk+dQ62XfXrvHyznfVF2u/bQck+3BiyH+0SU0O99IC/jEXzGnTYXiMtZBM2en/sAa8lMNOA27zTb6vEU+c9Bv5EVMs7A5FHxydRt5Lnf96yFvMEHKD4BJlJCiZ42+L+MUW6T2dTEj71gzEOOC1VFqWGQamDNlaLYD+MIwbgv3VAPujI8GEDKE56YGbGLO1WpNfcz46G6+uxBY2Oj3/LFoQKS2MDju7762kPGmeR3fFzI0+MamQPgc9hKZn1UsfTuN8TRyYCFYgE/K7E=
  - secure: EPmjknN01lzTa3yLiYUhbiOrhpCoAL5Zx3JIT7yIPiNvaZ2tDqVH12cto0Qc5d4O532YQq/N9KQOXU/abfRs2BTtW5b9MO92nI8wPk16kUj3HKqWxkCbo1neV/IIp1yb9si0DcJhm4JlHf0/GB1y7Ae9aSpOPkGJkOeIZm7v5ENKXFWYc+L6Ljq1U65huZqKeJRMkh8yzXciIIIZszQm185OTohw/Pz5j0H7TZlwSN59o5R87SB00YQqpUbME0ekw5XeSndDzOup46hn0l34faPFXnPdfaEO4N9bNaD9sOHEQxt1PWMkT9qnahDzcgiQFEGbaX/PSMNr3u3Rk9ZHeNscx7gpqB9lLRZZFde9YoE7clj2DJPfFagitxw2OUhIbgxlby2T4bgfO9HmyANw9gBxjQXczeLnlDxSvyLs6zvpJiKABIMvhXCtcVaCZgsme+rtZe1YnxxRniOYqhquh+KkGBGwCjogtqNLmdT41p+S4x5u6L9LvHsD+Ys5YylMp4CpFaM1YvfA8hmDrrlbq1UBSeGGPBGvt/2+rN2GjG9b9iuYQQ9a6fNEUcR6DZu6jrl5nn+6cEF89RRqUJzgzGZfOKQNWpOtEI1LXKWPV98jSRoWvigHAilwCDf0QpXfWJdegAunYQndKEUkE2fyjP2aYdzYoVH3VkCF8v8TYzs=
  - secure: GXh0s54LwFhaCP/mprTNUbWbMrypK1IC+y74QDR/VzQa/l0iDnQffwDdv0bN9s8UhnSJR2jrzAzJ760/W6lAeDZkzZSTkgYI9Fg636gjY8G39n1vGSYeTEBmflbll7Om96nj6RIRPAec1MjBsv/n9cqgwIjaXq7e09iOXpmJm3e6nUkbZN3HSm//lqB2P2/A+0Pnrhj2tLiMUKTvRnJjKvVTHI/K/0uDoMbYij5AOyou4mIhADM2ZPDRPzSOwN1Cw6rK27URtaJrxFQohSHD7e1HVVtaaw2mUFgCnj5WgRQI6MyMlOg7ggvCe9F+goocR8qsT6CnHl7c9L74mqnxCrAcFNUMvED/ordNzmRhsX074EzUBAdoW6Ntu4DSetwNWZds8VVZeddt8TzCrZx6h/M12IOA+KOlvGVzWHyofqd+i/skwSZarihhEF6l/3pqKdqRXqey4z6L+6SFODMvvWsQTzQ+01znrYuKsB0KoGxCt2a75AUaIQgPrNinbTLRqIGeudlKpJN3NJSpwp9mBqyL5BK5GJ7/o9ZQJrmSvh5cWC42sZ+Hn06eqMAsJgT9CtH5kypntnD1/aJN6Sa0aGCboml40pR563VSpUUzCMPaiI/hmqZZWg8TTn3E453rXN+VlCvZHErxF/YWjvMtDzb2bXWfHZKMI7xO80MnTVY=
  - secure: FxEyNrpQ2KmrvomMD0GI32zf3SJDPf1ZIK8NJwWIymAc9U5nggxsZETZM+jfspjo+kjy3h+2PxFMnf3sfW0s9FXMw2vIlQP0fkShm3lac/XCWwvLhKq2WYugXc0+2kC3BE8KguAw4+O1b1P8R7yO6E3MczkI9vdpq76ouTWD/79Pd3AkdVMdxHtaSNCOc+SFfSIRVJGoR6xVq2iGCA8q7pq703ri8/JnAuYqDPSNKnryaYc16y1Tt1O7iE8jW8o8i/Em/WDgT8LzC2g7MJTYMZAwHIU60qoJkmXo71zeXt1kFZof6WtyS8qfdTXtpWmqe1j581qI4SEbRLRInX9WUbpE/g7K2LqBWjEd7YEhrvnm5hsKxcA+yWbZr+t4Mq328pgfTOOEIiYs2Wh4oaObD1s4a39Sadq4RhJ9bWwhO5OJK8gUP+KGR+uMpjrXon0KCDL6XsVvel5WYWoRxZRuEnXtB0litzpGhtnSrICxITGcV5y2dfhHJXWKQAZwxM1GhfIg83MXxnm10Go5uaohvzux7PltdN3MZCVxSseucbTXPtA30L2XyL2enfVXa5D+9sMxkgryf7RjV6kmaR8wcQDfK3RTZE+3T7SZ4hS2COS5LXsRjgn9w9ZfuS4qBLgBin6wBoDk1sea8Td6yyKbMOB8b1M5gF32UzujMfZr14U=
  - secure: PV7es0wGn+V1yzqYnnoEGMwpfWv6vdEfE37Z67Ys6GGyyRNcHUqdFy7rcrrZLpraSZIUkSLCqbZpoyXKvI5i7fwR1SD8XQZcuIbHolrsFPRqMlqb4tEFHWNFZjX/yKKVLdftLgww5BNsi7a7ZZ3WnIJGQIhKB74CzaRYKoPqbGzs65s4RXhWewM28ej7QyNgc/U5bpfXXlT/ZgilgZ8ZMul9/ecjgqChG4owbE/fLLszhuaAys8SGkGHOpfgFI/TPlvXWZ3/9yxefZK1uvba5S/wl5F+5EeJ9djDgkBlT7NJpfimNWG+b/vACTLng50MxxKcx8Wzt3SJJ4by1W5HxdHZwTjMtm9lLChWCG1RU7ua0G+Pd7I2zmvQNqZK15mpXr2pwq6mamIidT0oHfe8ZbioMMWvkDpYD7Zi7wkxwrHj9qDS31PJqRSb6Un7sANW7pQPH7Q3wrRifR1VEg9uRa5ED/LofvdQj2Fh31CUJ33kHOnzlWWo0lRiHcc8JBcn8uKaF5No1eRwcNxHCEfYrGNi0QXi0jx3qDPBNJQMRqsd4qALcfc/RllCILTYz+LjoV7rOa8F8jBqfaf/9Ni8NcoaOB+boSbtMD4rhz898U27JCtHWFwXRdRvR75OG3sdsb5Y+xEXZf9TGlS/JAY7rFxfZi5Wc2E5sCNb8LnM2t0=
