language: go
go:
- 1.8.x
branches:
  only:
  - develop
install:
- go get -v github.com/spf13/hugo
- sudo pip install awscli
script:
- hugo --buildDrafts --cleanDestinationDir
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: tmo-opensource-website-external
  local_dir: public
  skip_cleanup: true
  region: us-west-2
  on:
    branch: develop
after_deploy:
- aws configure set preview.cloudfront true
- "./cdn-invalidate.sh"
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: MSToRR4yLiwEddkQMaUMxReVyCsdnzqEG5NMM05VOa5JWRLKZyE4QKqvLqvRLoPKQ0FYVGzwbsnDZEc2Zi+2uwvWUV4Zz8/uP71kExRS8WgOuxF6aVLzDZgf4WSrc67DKVT0BtnoejI4PtlE9a119IfY8jHtQQKXaNTvks7psXXqMesGtOz8G5n/qiNbNuITKjQj5ZHg/pRj3orZQ0GmfFP2MMaHrt6yvmLqnCLfb9aMFtX6Ha0QNJJxxGiZwnTWf2Y+WZ5n3KjWQT9+mpfdbTQ3PDvxdtzzgG1+zOyQJzlgSy6RhPlFgII50/LdwgUXf54syHghd6r8F8wbVXBfaqheYivl4QQfab7HBnnJneVzbRRZPYN6m4r88zxLa+ZsBYTfR6YYuOFuC32crlc4YTXTBrQU7eraBFc4Kv5ZpgOyypA4gNOXi3eqs6lhPtjnpMXozVkkDY6bZVCGRp6XqAzYIdMdjrosHK5XxVBAFLM5iai9LOXq8VpiVMShvkV2hIUBfA4uGt6qAg0w40UQ+EZ55KhTEOjvedSjFR5okB8t+08ZHoKjUX4dOPqP1HL2Mp1DASjdjKSL4+TgaJt1LyWWi7ZMHDkRgDCTT9ObxZusuFhFtH/WlHWuAhD4PH5oFmhEsbb1IeU18damt9+00/CH+cq/sJT3kfmF5+86we0=
  - secure: CR08Dn0DfSKZryscV+a2UOOV5HJDwfs+gfOj0tDnhwGcDrbxz81AzuY3u71vj2MDdgkTSAEwLbn4Rcspc11XQEImBv8g0Qg1SA0WNwM81FSgXlSzkUmkp+jumKI4SJa+BbeoiTB6nEkJdxZ/ofRZ5Nu9vyndIlqFhQ79hlTZlWBiDT1GwwUL/OwnwRnxRUeee8emy/B91dHJCro8znSJF2K+Cv2CK22WqFIc6ULbL4JD23CiN+RCMSdysu5H0Ikr9jWXLRwglrzo/Gp/Iy4o9G2VQnph5ByKKmgxylFEAOXyuoDpm0Yt0+I9NBKcH+z4zMSueHHJ7tTdmfb7N35E96dckf11VRTjrnLpPfQtpCSlTy26bDcHm4jaT7wHZTgnW9OcD0QHfaQpL3rViv7vVnNznxVsMe4RIktKb3kpZB60rDLZ7o8iwl6VIeBJp/pqRafGjhhOUi8tqrSIo+WubzT7Ha9vPG1SI2rwGHbvJsjBbn41dkuD7ZxcEpqbLycG9NKflB09FQOAcLQtDzFpZuS9c6ohy6FGWufg0tu+sORpD5qSPIwr8cfV65rKGdioAWWC7TEdYBvRsmhNKXRwxRbKRxn1K0g4AH1RK4LMorrGSU1hDJ18dcTHokUbc7+mrZhhxDBq9utnbHUpPBEavaBLP99n8Oenkh9O+1uuvIQ=
  - secure: setRRbuS9U1X6M67u8F7K6IZW/M8aKIUtHEK8/YoQ7SeECpv1wNanEx1ZteAWwRE1fAGRcUvOPIpKhNvOWdFYx2NSzj8jZfQyM1gukwOZ4j6pZqOzexxOt0SE7sVoMcAX8jMgZDj3wDAa3lVA32ZVWGuy1ip4kMMAcR5t6IwSJWpNpZg2pRPxMOCZff9PuIHTqS+hzaw0bIbo5oqAEj5t2rZgI1gZ9I7QmN+6ki3/0kQLoX22WjQpsc19tJvQIGVHUi5MO/Y8RDY6/eCxX4xvHbMKOkP4wRIF+U6YKhXG+ua7PKhcshX6wb1LvDdIctcUyRH0Slsniirhaz+a9lx8RvW0esiR1UHsW9kEr2z4UJmW7KhkB+GweawfeovV5ycRjZJ9L2wfc47JKiSqYRqe79hPBa213aznSXaA2U79HlFJ4V3CvPqe72vgdhgloLlY27ripAQvj8Isn/SDSeux0wFpsJQNckV0ngmsGqHHg6cbFTGzDe+kZHZEHqkIrw+X80hWsLs/oFYMtLBYKu5PTbQ11SkbcTPsPUw66vET/nJTzlG/YwNCrxFqWN5wi7ljfuol/o7XMelkRb9LW+MWnlFnaU2CFTEk0rlRiWWtHVz2R6b1L8DMbNW3hzzExT03ZWrk94/e/rc+ZXS+SeU0BjwCpJZzuznH3X6rM3W/n4=
  - secure: IeEkKLmSDN9K2mM8SiwwSPgwkD7Xe3TygJGPsfeqtpe3tzPhuExiZQMO+ghJ3lG+9CRormhFgmQNUtLrOeotlFW0BkmpuPLZs1cXG8QYtIBZI/X4ZUC49Fwmunyi22jUpmH2fzV1CoPAiz780mKo2hDkQQ3aD/4w5Fy/amc3dICQsjSkN0a/RFa87KAlJgNeXFYg9CqJGexMUrXkDHikCN8pjgmDEmu0bBIAvuVF0MnAqZl89nWcouWj/wFWsdYiur0xKJmCJg6mhJEsg4wX0AFUPXD3pMV8r+cxwBaN7uOCdBIPxq4e/xVJbzGfESmziRDZi/GAKBkSvWjzOGB83bA5a8GW2W2whPBzxKVSq5IghKrujiBfXE0IQLGWnBglIpWhYfKFjWBsiU1D90Fi0ygaFhuza/fTmVomsC4VxLZ2YJt03pHWAWOZ94dSmwNjotN/Wn++0Zxeyi2t2UZLiu1U5tNmUEHaG5GSPWGk+262Cl9YQcYCBqOFCpnVD8Os82Xb3kuxXiC3h6l+bgS3G7O3+tQwRbA3gwdrvCxVzQLcokWC6ygZy/plxdi/FpFqEoV7WFm/gKaoR+bb55Vn4vgfciA+fCKYhQKtu32ldLMcEYm3g6+mbXoPgJQ+MEOMYreL90ZPjwDFiEdk+3mPKBCQhO3v+S/Xbf61VRaU/eg=
  - secure: lQRDCkw3OYHbiuLVZq+sG6Ugrv/805FSyr532ip0E9vLqvSoQQONKdkilglp42pkujxws3SWeHlPohNnNkyLLXLn++NVXn1KKcEDDL+y9wQ1yJpcCjGt3wpRpBjc5R0YkRr5tizj9KI2+OIDeWHVy4jQiLAgrkDGmOAsiDEpZmwb9+hD3BlIaSQSxskcvlKdDxAOfWP3u13MHM1b6PNCRspfGKQhacJcZqL/ae3ngXf/qkqZx2R/aK7NVMh+SGfeU9OMy3C9CSfIF4U9GuTz9L9VARvSeHFyiegvSqQmxjKTNQm1vTeQJn43b+G+A9JYKwgE12Jqoxp6PoBtl0gBIf8TehGvXT0kVYl8msCIRZVQy3IcFq798UgiksO28+v5U3Z/xCOxIX+NSfNKDVQyvNNc3JLayND6w7bfqTswhcHUGxEyIr2HSraB88nZN7dlCACm27PA1QtE/7gK5rug9OTDYinkud2JiqURytWFShv5Vn3o5pB6J+RTTTgRyuLT12FluwXKVnwDhFWr/bm0BsMaozrJz6Ph4ghEMCZP09Z59EBdGw/+DV/Jvdv1ova1wKm0+H6XuVQa3zP7f2KaYWm0PzRkUOYQLIw1DxamYlRYNOOmGbTjeUCPSIqd+BkjlQds/3wc45snS3iofVUu7jjYV5zliu1AfyvpGhpsaTI=