language: go
go:
- 1.8.x
branches:
  only:
  - develop
install:
- go get -v github.com/spf13/hugo
- sudo pip install awscli
script:
- hugo --cleanDestinationDir
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: tmo-opensource-website
  local_dir: public
  skip_cleanup: true
  region: us-west-2
  on:
    branch: develop
after_deploy:
- aws configure set preview.cloudfront true
- "./cdn-invalidate.sh"
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: CdUf5pyG1zXVisM3PDOPRGENMdZ64QmlGKtPLrbpFzOQV5sz2mUH2CtXyQiK2CLwuB57VXvVCvUBru6MiXZaEqUCOtvwFa72CrCHAKdS04bVxCzNKIJ1eOLO0zxsH/KMesrRWEGFFsZ9CQFk6GEnQIhBnX1omrj7FElh3Ovhb17ChafCjEhBScSE12T0JuXCYgzSSJcDq+X0uWSaXQqEEQTV5spy7Mgvl+YgE/mrcyIuPTKwnj7VsWU3kZcqqUlzpKzTP3RLcIaccZ78MIJFFwfILXdeUSqRuuIsiTDFIUb3Wz7dm9bylDF6MyHMt+lPDXNNlUS4ZQwQtPHIgQefzahvMlTqFUGB3fSdP/0dKMAd3//kq9ji9gej8UfVT3GCimgzRj9ZvyhoWQYGpB1KnmNFlJh4/J6cq3rTWg/hG+Lt941gTMmDby+j52VwgVzzFGTrjP06d1+3P2AjJLHiArcrXtRqc9XABqzyc0xOsJJ6jKf4FwYLEwzX9+bja6ahMkfHndOD3SYp40JUbg5zZbBE+16fd2MPC9h200FjgSVM/4EIiR7z0b8ZT7fTVbl3xdQY6YXr7oiinpXKSFEq+PhmSu5jb3j6v81d1nRUImjTx2XxRHLfrbRqqq8nyFdTShPbtFSa6TuS5NSSpL8CTmJa3sJMdMu16dYx0PCgvF0=
  - secure: VRl7R+iYSahUeJ/576S4xsXH8KBdhVpzq9LX/2RMTircdEljVr4HyDYFMTPuXgzLAcL1Q4UAlwZ6Nth34M5SOPACX/jAKen8Vq0GBdqTX0zRPHvCTYPzB9CRIkrrb30+eFQxdolhlzadTgsDOA4XinWvbTM9tpTlcfQaEf+rWMa3RBtinn4OADyzd/sIjKGr2GrzwjdmqyO0RZcJ9IJEeZFMMB9XMU/z5X4PlsYKJbGdOGZ+nh2T2xD7TSgRgB+QcTYtCZ7AD3JvsIF3+Tt9aCeVv4TBHYEiratqgPLD0GEXcEzum7xYGoj3uarXiq6PhHArZ6AJAQ8sH93pFNAnExvmO5OatByDJtZGNy6q8bRVYdEu0v3PMz74VxHcgoG2hOdGFGtbfH3a/TJKlt3cv+73oemBJF2hVETTI55SR9xhTnX8Kx7251h3z9pUy8qo3OWFZexlGDSwF8Z6YrTk6Wvds8d2of6E70EsNvL4+MNyZ8J6HAVWUH7EAaeLLswn9R50dlL0IyBES/xppGrT6Ed8hynRh0X/PaP+vDukAReL6oYrPkr0Ymqs/Vc2+gNe8ObH4AKMUiiLnI8rwgTqfmrVluA8Qun9GgyHifh4ZvOiWvXTRj9UQ0BaRaq7IZCJi1evJEYQzXFHJ45Cj8lCfPjXoEj0HQJ3VLkKxsFRf6U=
  - secure: ibp7IC7/0irv2nNoIOax/voMSBdJoIN7IrVGGiONPFJXpaAUYLj4gDQTq2YwkuMeFZK4c4Huf4fUr4EwmcGdJisALsFoJS+7xKUNBKC5kHK7UDUgyH25BXFwnrOxBXB+R4dYvrqH6y1KXX4AAKoYQmTm7SMrsip9UrN/uN91S+NYPwoBB6spA8ZnXFn8yguNu7NYy3Vs2ZIoV6p05nghg9NShwIQXpnY4pJjdSD9ZxMdv/WNFSt0L0o5A17CQNwFfwgxpRNFcYx11eZwHkiFop/gEI97BSynrpAO2AuL3+pSicYZcEFLgmwM70hjI7cSzX3wsBvl7gfXWNpJZe/dNNn2EC/3BevpE77RRph8Iw2phr4xpdD1AKb2WZT35cLOfAwf6rs9pcyWIbTUzFLTVrQpZCXpZluB4iyqB9JepbjwxrgZnz2xbR8MNbSsGjZkzVx31l7w2fg9QaPNoSA4LvbqzKR/mv5WdfBkEXbiii/QLGmK6hmM2euktMuVE+OOWesdzluiSQS9Cn5nD7aPP4gPMft1AB/LeOVYLFA10fMrfeSBXbHdBbEPHadN714I224J3VolotiCQkxwcFTzYdGUHRuRDONvL3qIiDNragQb3VfqADz4KXkfNBV9hoAMcY2IHVr4SP91VWegUcZgj4i29bOqR68zNuhJfwp/yHE=
  - secure: DR5Hv3lSF2mfq40LqEbSEgNQUP0oXq5OWg4CgOtzkFyq0Ci1Ik9VZ1HgLQaaweHbl0WA+jXv2TOJ6jQ0nS5mGMQ84NsHCYWnvlnQw+I4Pn953bK1Ulrkzfu2HRrabc6wz1Y7ukYI8P67hZTtVUSxVg/ytTri1adCboQplXpPs84K5Av0YFfxrJU7IXseRWl67dENvYrs8b7Gx+Dc9JP32V9BwCucf2dlxMe+ZTybFQfBIeu3FizhekHlLoKeGyIyQdISSNv/dOezVr2TLDP7O0bkFn/xUieOT2Rgr9Y8CVEc0jam0GMYR+12+838ATLP7tlzop/M7Zp0JHYWaBEwiOGr/l8V26LepbF61oo/Lmwvm3Cduv2FhuQu5ptR+gI3rtWi0+KL+2hZSMYJ/0wy752vJix23UvrOFa0L9y3bz4xqpal8RAjFjHsHWlM+pSLoVdFxT7it2Pz7S/77T9Jy9Ed2c0QwClIgkbZI5jL2HTKrMr0AcX0I8q9UD1TfBqtfEzrnRBjKLz7RHmBtuhzLtDK4ERJrObYJVGjL1DABG6KMxAeG7YUYuZvs+LCiL0giF/w81mG7DclCp0a5pjIAfEtUehxc/PKTGk4/qQWwPZ42GkZx5L7Qhs7xVNRUKpYH8Et7KebU68S2inL2pZsTtK1snlP5gJk6cews56LWg4=
  - secure: LEGGe11/OQQf4gdbWMxdFzJzYo5SwKiWkTA3otewVcJrNIdwpmartEk4VLZZ3wyx2eZw4jj+6KTHqUrnTFhYHWZxDt35m9xoRXHNZ2kAu2CcHhHF70Rh5X0XdesKOQV848vKPlE5n2S3nRHtwJgkXRBbQS7B+oV9pwUxodBtwM4JX6iwDjPmmGFLO3iCU+63x/3uQ8/izR7HUG54Cf+e5cBa9JBSAI8lVeGwZHryfwPXMeczWL4+dPAdCzBWf/FuNXxMHGn/N9f44q5vaJP3MnpbrN+dSfLW+++6wnkLiB9JGnYMTTCEYKupLxEiNcPyVDZuzojFPpkzrzm+QIPAosBFUWnuH3r49jjW2pW3tjRQ7JI41Q+wDMHoWyR+lFFse4C55Udw0s0N5eby3BT5yU46fLGJWnZBOU5BjcEZJ6tdXe1Li7f/SGJUl3+4Z7vw2YC8/jR2PYTEKn1a5spdSnv1UukO8wBcaQpbzPz6yEtA/tGlO37CtavH1TFiw/wiipXloCj0UboDxVNbsSx02VQm32/2ZpJ0N1WGPkJrQ7JyCiU/JjjCPmzz8bDLbSdw7yDIoxWo+MgH7vNAjas3Y4k1TV6oqIK7RIdH7I0y/2Z+LNmEsnzNo+wGNCPQIvpAN88Bo6V9BQubbFQ1piIWREVwkig2EXh3/AjVOXEuHbM=
