language: go
go:
- 1.8.x
#whitelist
branches:
  only:
    - internal
install:
- go get -v github.com/spf13/hugo
- sudo pip install awscli
script:
- hugo
deploy:
  provider: s3
  access_key_id: "${AWS_ACCESS_KEY}"
  secret_access_key: "${AWS_SECRET_KEY}"
  bucket: tmo-opensource
  upload-dir: internal
  local_dir: public
  skip_cleanup: true
after_deploy:
- aws configure set preview.cloudfront true
- "./cdn-invalidate.sh"
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: Ockki1wyR4TDYCczOYVZqdAF3vd92dUJkTEGewBU8p9LcOUg6X+U+vMboDTE9IMdcOy0z2v8JyXtAjBHbAzIK0Znoaxd6hhyIWnPdy+ZvQZvI3ne0SNEv/SuKBQk9wA5YoQQwJ6669iu8nn4roHrKvAF94+pYR3XtDt7++sbeHCrVeRKvKHIo2mDLIMqcYe6fK6DUh+ttKUCEG1lXFwjYmJ+ra01KpqysTQj2CrUAl7vntjmnUs8/Umx0vzzV091i+ZRBgwsHCvHP4nQf/Ja7G17GEul4YJkhkBKif3ZN3nM5UU5WCb2g4mS87t/T4nP4DiyLplYJOB5KBI7p5cAxNEM8xsVFd6GSkGjWi1PJ0TbrZ/RvqrBkU7gvlbCqIBm+PwKz9+yrQ9c1IiLiUzXBLdnkm2FqwaWCSHpJt1w6mUDqfj0GlGNTFTDjF8B7sRahdZfz3Qaacre33hOxZOfgygCRS/jU5Di6nfl8gsztrluJt6XPq8NLEDEVwB241m4fFPQqqe4xoaVNO+w102Sha8dWKbMWUw52P0ok0IJIISV/O1iVmX03iWA+K0W32louDsZ2Qafs0DpktsZPSYSxdCq6kuhZrAiI/53Zswvo6rBWAvlGH5eSfxJgyd3HPOMdJGlZK1S1c4Ld0Zb3I8SHq+yrx2zvkEeML+VB05rcWY=
  - secure: FXt/qPgnrNRvo+joyv/S1T5rQZuKivHEC1JIsvhplBmHQe4W+YRnt2zQEYe0M+XkBLdxIzJnQTknPaYzX6tZVytUN6/2Jr9CWTWYPyXKSo92SjkoxhKH6donpSWvkHQZovB7WPNj7qTHwObQdBNY79e7rOHWaGMRyeGKN/EBQ4gAuLig+Rr2hn7NYCbwFVx9pH4EGuO1pioUT/+L9PNy5Y2Xm8t8c3J6VtTVhvOMa9hqSmBfqtIyWN9VcwFulJ8sg37En9XkQbuBrt47o4y0tD0qPZQsrhlurcR86cgtIrCPLHDqoxoRH3Lp8TxhUDyuFKv58r8LmTBGAjNFEVnz2qGCec0nV8zqWamjuiwyrdo/FFYHf5JiPil3kZtah1ezyghkGoLf/fdliab8uIdC/K51ogLFaNWMz2fPDg/0kx+tuMyVKTqLlsYeKBtUEjCt/tTQyLeckyd726edhLaPfWt0zPr9sreZ1Vd5i4983ezJUTdYgu6v0614pDBveWiK8GPBy6korZXQxPO1W9eaxIdKgsn4Jl4cdifXbNa2IogOXhm5248FK63GiOZ5B19+zfuPCVCo8MXRoupeLSl7CTkx6zyaBQrr9XKG3Pw7FoiMrG8TfN4tCmSusGWLoqQ0hyy7mdfDzaLBMnwtuatioDlp+JDQNJ/ySMDyfEG4NSc=
  - secure: HxwGebkclhZ7PWe5HfC1avEZgHmrH7vn8CXsL81z3K2LvDDuxoFBEWh7uaibfhHTR0VA8sOrf0ViQuAyzFWEsYbFps2emI/SS+qYjnd+D2pJDL8Tf4zqoCm4xhGfDIZCuqzKyL60Qea8IFRWtO4jKaEFO40zqjxqAfd2xCqw8yl6Uu60eGiAQAKs2XjF8VuXcg20oyLkPT4SVX1+nhRbc6/o/D0ZUs9GZdVlE2++NRpoMddDRAmsQYcFn2BkF4KGKM8UcpCD87/dj+auhWTSEvjGFqemnR2wNO8dW+wWJOOtrR6+HKSXeudCBqoFMF55e5OtlCSjWpG2LUc3KJP2/nr4+1a2A6bl1wg2xm4vZb3sQVysaRrzF/UrG/NeFf9rJHX5WlB9sKM24bhq32DhnFRUDYJEeZS3mmuaoTrlOMkZElWQzfSnHum2LF+FmU9ap1MfKvfrMj764gbq8pW0gHTiegOWYkHFYg8EdAklfeBuz4mQhLrGyqKbp1DmkH8WQI+8XyeIrDUSQLj9juDvUWBE//rOeb7zlrDP0z9bWIOdodQoTfHPrUEFWZm6BNb/fGSocRPxVNhc8seK3yvBQl3jFL9KelfyW/OWtmJwk3Gn4vEKygrYvuWgPVve1w85WEpR/jhtbSNW++B5ZwT+Sur/IWlzmmAAD/8MlMo4RIo=
  - secure: NlR4EojIBVGuAUpoqM7Z7Yz8i00iDYGhbivgcY4drQ4V6j/NH7KTPe/nZgboXdELPg18AFdBOCdxttYDJ7WVivg6ckqvQMjBwfzx49Xta+faeHe2JqPZznEqbTdDRS3vehkYiOY6fO2+iQmerJPFmKIuv5DkN1A3fydfI4mpGoDxr14YUVrtPcG5nrsKsJYqT0kziahFprbITfWnSaYVjnqR1lz6dAJa76IBMHI2zqRRrIXjwLnVhrDNDxQhbCnhHqEZbGGE+EEtnQH3rMgo37HO0SLgA8+0jXG9XcMlhVLNwkCoNjz5I1BiD21WgtQ6yTHpwcWORB5ebr7pJoWW36rctFZzr9+8am3NTBKjTpBbq+e0DSZd+UCvhmUk7bc+ujsIU7CtVjnAO9vXnciGxWygmEzeI0mELDmRnQbTRcdooq4JIu00uPas3U1qSGUcXsI9/it93+vb6Og8coOskD+6MuIIdcO75+DhPS9DFuZDkNPKDa2uVy9MAn/uUSuQO2Uh7bckC0ys7Hgzt40Qq79tS+aNqEi/0kEuRf9d6JbMuN8Jd7h4J+9cmmntF//KjrrjP+nuQ7e/48oDvx/xnBp108LW02v9BhZN/eCVvMGYSI9LjE+v7QESFIUeR4yn03RGE/b5/GSG7XsbjfSrgrq/fAr8lyiXogxuoaPhL70=
  - secure: rROigeg3femNKDlsrPJsobke1gB0Qu84E15F1NBBZ8NuVLmbtbxyyb+VD6A7k7LQUYZx2zsTxlF79+MwYG9gJr85z8SwM7xegEC4/8P/9dB+vlCeT2flDEPB4JmpyQV2I9y3SihakyFYF3NyJn37jLlc6PAZX4bDWUnTqEbVghaBwk/+pZtIa+m1BZ3wcQYU6DwLncDhRtmmeUDc1QDBo8ev0cQIhv1L0hgV7cGfQkyfp2gTT9D7ahXn+1W3lpWA+4ai3VXZognHX1Dkk17QtkQkY6dJtbwBTGJ/rksH653L6IFf9jEvmN/8gv8V6QtVTkUdubc5cx2ohx7dsHy/aijKaMH5MRJx2Ev6WFzFZ1cUP2F1SH6N09SSQb3E763CXKHZLa7ehOSInYBguPRxKkEmnTbnx591JTZyc0H3oGq7wZO7azNaYhgOuaRfdtYXC+uIUNFVnH+Ow4EiArD4MDlxyY36rZFrh+1/m5UB9+CaWDxGPOqNcQNLlhDZKRSo/tI43X7QhIFZqxo8z41zfLDqEeuojFBHaKlS/+3yUJ7Euhiq/HkNqFLXeBZ6GHUY7YoXMvOcKDeD46VfQbHW+G/8xk8yJoD6SNMbt6LS+Lq4inbpsPLlxszTKMCg2vfcnLO1uxn42aF5EqMz4OliE8OuYv5Lv9UvPUgibKoyS0w=
