baseurl = "http://opensource.corporate.t-mobile.com/"
languageCode = "en-us"
title = "T-Mobile Open Source"
theme = "tmo-oss-theme"
googleAnalytics = ""
disqusShortname= "tmo-oss-internal"

[params]
	org_name = "tmobile"
	name = "T-Mobile"
	description = "T-Mobile Opensource"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# footer
	[params.footer]
		copyright		= "Copyright 2017.All Rights Reserved"

	# Hero section
	[params.hero]
		headline1 		= "THE"
		headline2		= "UN-CARRIER"
		headline3		= "OPEN SOURCE"
		slogan			= "Providing innovative technology to the community through open source."
		[params.hero.cta]		
			text 			= "VIEW PROJECTS"
			navigate_to		= "#PROJECTS"

	# projects section
	[params.projects]
		headline		= "PROJECTS"
		description		= "Check out the latest projects created by the T-Mobile Team all available to try for free on GitHub."

	# About
	[params.about]
		headline			= "ABOUT US"
		description			= "Interested in getting involved with T-Mobile? Check out the latest events happening near you!"
	
	# Code Of Conduct
	[params.code]
		headline			= "CODE OF CONDUCT"
		summary				= "In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation."
		[params.code.cta]
			text			= "VIEW DETAILS"
			navigate_to		= "/conduct/index.html"
	
	# Contributor's License agreement
	[params.license]
		headline			= "CONTRIBUTORS LICENSE AGREEMENT"
		summary				= "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
	
	# careers plug
	[params.careers]
		headline			= "INTERESTED IN A CAREER WITH T-MOBILE?"
		summary				= "Check out all the sweet opportunities T-Mobile has to offer!"
		[params.careers.cta]
			text			= "VIEW CAREERS"
			navigate_to		= "https://tmobile.careers"

