baseurl = "https://opensource.t-mobile.com/"
languageCode = "en-us"
title = "T-Mobile Opensource"
theme = "hugo-oss-theme"
googleAnalytics = ""

[params]
	org_name = "tmobile"
	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "T-Mobile"
	description = "T-Mobile Opensource"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "T-Mobile Opensource"
		[params.navigation.links]
			projects  	= "PROJECTS"
		[params.navigation.footer.links]
			privacy		= "PRIVACY"
			toa			= "TERMS"
			feedback	= "FEEDBACK"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "We Love Opensource"
		subtitle   = "At T-Mobile we love opensource and community"
		buttonText = "Find out more"

		
	# About section

	# Brand section		