baseurl = "http://opensource.corporate.t-mobile.com/"
languageCode = "en-us"
title = "T-Mobile Open Source"
theme = "tmo-oss-theme"
googleAnalytics = ""
disqusShortname= "tmo-oss"

[params]
	org_name = "tmobile"
	name = "T-Mobile"
	description = "T-Mobile Opensource"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# footer
	[params.footer]
		copyright		= "Copyright 2017.All Rights Reserved"

	# Hero section
	[params.hero]
		headline1 		= "AT THE"
		headline2		= "OPEN SOURCE"
		headline3		= "UN-CARRIER"
		slogan			= "Providing innovative technology to the community through open source."
		[params.hero.cta]
			text 			= "VIEW PROJECTS"
			navigate_to		= "#PROJECTS"

	# projects section
	[params.projects]
		headline		= "PROJECTS"
		description		= "Check out the latest projects created by the T-Mobile Team all available to try for free on GitHub."

	# About
	[params.about]
		headline			= "OSS WORKING GROUP AT T-MOBILE"
		description			= "Interested in getting involved with T-Mobile? Check out the latest events happening near you!"

	# Code Of Conduct
	[params.code]
		headline			= "CODE OF CONDUCT"
		summary				= "In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation."
		[params.code.cta]
			text			= "VIEW DETAILS"
			navigate_to		= "/conduct/index.html"

	# Contributor's License agreement
	[params.license]
		headline			= "CONTRIBUTOR LICENSE AGREEMENT"
		summary				= "At T-Mobile, we manage a lot of open source projects and we’re required to have agreements with everyone who takes part in them. It’s the easiest way for you to give us permission to use your contributions. In effect, you’re giving us a licence, but you still own the copyright — so you retain the right to modify your code and use it in other projects."
		[params.license.cta]
			text			= "APPLY LICENCE "
			navigate_to		= "https://www.apache.org/licenses/LICENSE-2.0"

	# careers plug
	[params.careers]
		headline			= "INTERESTED IN A CAREER WITH T-MOBILE?"
		summary				= "Check out all the sweet opportunities T-Mobile has to offer!"
		[params.careers.cta]
			text			= "VIEW CAREERS"
			navigate_to		= "https://tmobile.careers"
